const express = require('express')
const morgan = require('morgan')
const bodyParser = require('body-parser')
const routeNav = require('./src/routesNavigation.js')
const cors = require('cors')
require('dotenv').config()
